### ISSUE TITLE
release new version with diff_match_patch 0.4.1

### ISSUE THREAD

**Issue by felix-ht** [google/dart-json_diff#14]
If have seen that you updated diff_match_patch to 0.4.1 on master. However this has yet to be released to pub.dev.

**Comment by BellRampion** [comment]
This is an issue because other packages depend on the newer version of diff_match_patch and thus create a dependency problem. Any update on this?

**Comment by fjwbarnard** [comment]
Closed by https://github.com/google/dart-json_diff/commit/ac8cebf33ff365d5a75056475c37ce24b125aaca

**Comment by srawlins** [comment]
Thanks! Sorry for the delay.
